version: '3.9'

services:
  postgres:
    image: postgres:14.2-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
volumes:
  db:
    driver: local
